[project]
name = "proyecto1-optimizacion-rutas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "pyodbc>=5.3.0",
    "sqlalchemy>=2.0.44",
    "streamlit>=1.51.0",
]
